### ISSUE TITLE
Does jovo cli support video skills?

### ISSUE THREAD

**Issue by geethurajasekharan** [jovotech/learn-jovo#18]
Does jovo cli support video skills?

**Comment by jankoenig** [comment]
Yes: https://www.jovo.tech/docs/amazon-alexa/visual-output#video

**Comment by geethurajasekharan** [comment]
This is Visual output into the device. What i meant to ask was the Alexa video skill: https://developer.amazon.com/docs/video/understand-the-video-skill-api.html
We have a video skill i'd like to script using jovo(since i'd like to replicate the same for multiple customers) which plays stuff on TV upon receiving audio commands to play/record/fast forward etc.
